version: '3.8'
services:
  redis:
    image: redis:6.2.7-alpine3.16
    restart: always
    volumes:
      - my-redis:/data
    networks:
      - webnet
  web:
    # replace username/repo:tag with your name and image details
    image: localtry
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    networks:
      - webnet
  flower:
    image: localtry
    command: celery -A celery_tasks flower --address=0.0.0.0 --port=5566
    ports:
      - "5566:5566"
    networks:
      - webnet
  celery:
    image: localtry
    command: celery -A celery_tasks worker -B --loglevel=INFO # -B enable beat fro periodic tasks
    networks:
      - webnet

# Names our volume
volumes:
  my-redis:
networks:
  webnet: